
# NOME DO NOSSO PROJETO
spring.application.name=projeto-spring-boot-com-mysql

# URL DE CONEXÃO COM O BANCO
spring.datasource.url=jdbc:mysql://192.168.205.100:3306/robson_d_db

#CREDENCIAIS DO BANCO
spring.datasource.username=robson_d
spring.datasource.password=00078519

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update